package policy

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"
)

// ScopedAuthorization is a short-lived, signed bearer token that
// proves "this principal has been authorized for this action on
// this resource by the gateway, valid for this time window".
//
// See TWO_LEVEL_AUTHZ.md for the full design rationale. Quick
// recap of the security properties:
//
//   - Time-bounded: tokens have an explicit ExpiresAt; expired
//     tokens fail verification.
//   - Use-bounded: MaxUses caps reuse; the verifier tracks
//     consumption per-token-id in an in-memory LRU.
//   - Audience-bound: AudienceID names the plugin that may
//     verify; tokens minted for plugin A fail at plugin B.
//   - Action+resource-scoped: the verifier matches the token's
//     declared (action, resource) against the request — leaked
//     tokens grant minimal authority.
//   - Per-spawn signing key: the HMAC secret is generated by
//     manager.Load per plugin spawn; secret leak only forges
//     tokens for one plugin's lifetime.
//
// **Wire format.** `<canonical-json>.<base64url-hmac>` — same shape
// as JWT/HS256 for debuggability (`cut -d. -f1 | base64 -d` shows
// the envelope as JSON). Distinct format tag (`fmt:v1-hmac`) so
// future formats (Biscuit, M6) coexist via tag dispatch.
//
// **What this is NOT:**
//
//   - Not a JWT. We could have used JWT/HS256 verbatim, but the
//     simpler envelope keeps the format tag explicit (we'll need
//     to migrate to Biscuit) and avoids dragging a JWT library.
//   - Not encryption. Tokens carry no secrets — they're verified-
//     authorization claims that the verifier matches against the
//     request. Tampering is detected via HMAC; the contents are
//     intentionally readable for debugging.
type ScopedAuthorization struct {
	// ID is a unique identifier for THIS specific mint. ULID-
	// shaped (time-ordered, base32). Used for audit correlation
	// and replay tracking.
	ID string `json:"id"`

	// Format is the envelope format tag. v1-hmac is the only
	// recognized value today; future formats (e.g. v2-biscuit
	// for M6) coexist via dispatch on this field.
	Format string `json:"fmt"`

	// Principal claims — match what's stamped on the request ctx.
	PrincipalID    string `json:"principal_id"`
	PrincipalKind  string `json:"principal_kind,omitempty"`
	PrincipalOrgID string `json:"principal_org_id,omitempty"`

	// Action+Resource scope. The verifier matches these against
	// the actual call; mismatch → reject.
	Action   string `json:"action"`
	Resource string `json:"resource,omitempty"`

	// IssuedAtUnix / ExpiresAtUnix bound the time window. Both
	// are unix seconds. ExpiresAt is an absolute deadline; clock
	// skew tolerance is applied at verify time.
	IssuedAtUnix  int64 `json:"iat"`
	ExpiresAtUnix int64 `json:"exp"`

	// MaxUses caps reuse. Most actions are single-shot (1).
	// Bulk operations may opt up. Verifier tracks consumption
	// per-token-id; max_uses=0 is treated as 1 for safety.
	MaxUses int `json:"max_uses,omitempty"`

	// AudienceID is the canonical identifier of the plugin that
	// may verify this token. "" means "any audience" — used in
	// tests; production tokens always set this.
	AudienceID string `json:"audience,omitempty"`

	// CatalogDigest binds the token to the exact discovery snapshot approved
	// by the host. RequestDigest binds it to the exact CallTool protobuf.
	CatalogDigest string `json:"catalog_digest,omitempty"`
	RequestDigest string `json:"request_digest,omitempty"`

	// Caveats carry per-tool conditions the verifier checks. The
	// keys are well-known names (ci_status, labels, body_hash,
	// ip_range, ...) plus operator-defined extensions. The
	// verifier consults a registered caveat-checker per key;
	// unknown caveats fail closed (refuse to verify).
	Caveats map[string]any `json:"caveats,omitempty"`
}

// scopedAuthFormat is the only currently-recognized format tag.
const scopedAuthFormat = "v1-hmac"

// scopedAuthClockSkew is the tolerance applied to token timestamps at verify
// time. A verifier may accept a token for this long after the issuer's expiry
// timestamp to tolerate host/plugin clock drift. Replay state must therefore be
// retained through the same window.
const scopedAuthClockSkew = 30 * time.Second

// ErrScopedAuthInvalid is the umbrella error for verification
// failures. Wrap with %w so callers can errors.Is for the
// umbrella but still see the specific cause via err.Error().
var ErrScopedAuthInvalid = errors.New("scoped-authz: invalid")

// ErrScopedAuthExhausted is returned when a token's MaxUses has
// been consumed. Distinct from ErrScopedAuthInvalid because the
// token is OTHERWISE valid — only repeat-use exceeded.
var ErrScopedAuthExhausted = errors.New("scoped-authz: max uses exhausted")

// MinScopedAuthSecretBytes is the minimum HMAC key size accepted by minting,
// verification, and production agent admission. Keep the boundary centralized
// so hosts cannot accidentally enforce a weaker requirement than plugins.
const MinScopedAuthSecretBytes = 32

// =====================================================================
// Mint (gateway-side)
// =====================================================================

// MintInput carries everything Mint needs to produce a signed
// token. Fields are required unless tagged optional.
type MintInput struct {
	Principal     *Principal // required; supplies PrincipalID/Kind/OrgID
	Action        string     // required
	Resource      string     // optional; "" = any resource
	AudienceID    string     // recommended; binds to a specific plugin
	CatalogDigest string     // recommended; binds to approved discovery snapshot
	RequestDigest string     // recommended; binds to exact CallTool request
	TTL           time.Duration
	MaxUses       int            // 0 → defaults to 1
	Caveats       map[string]any // optional
	NowFunc       func() time.Time
	IDFunc        func() string
}

// Mint produces a signed token from input + secret. The secret
// MUST be at least 32 bytes; shorter secrets reduce HMAC strength
// and are rejected.
//
// Caller-supplied NowFunc / IDFunc are escape hatches for tests;
// production callers leave them nil and get time.Now / NewULID.
//
// Returns the encoded token (`<json>.<hmac>`) ready to attach as
// gRPC metadata.
func Mint(input MintInput, secret []byte) (string, *ScopedAuthorization, error) {
	if input.Principal == nil {
		return "", nil, fmt.Errorf("%w: nil principal", ErrScopedAuthInvalid)
	}
	if err := input.Principal.Validate(); err != nil {
		return "", nil, fmt.Errorf("%w: %v", ErrScopedAuthInvalid, err)
	}
	if input.Action == "" {
		return "", nil, fmt.Errorf("%w: empty action", ErrScopedAuthInvalid)
	}
	if input.TTL <= 0 {
		return "", nil, fmt.Errorf("%w: TTL must be > 0", ErrScopedAuthInvalid)
	}
	if len(secret) < MinScopedAuthSecretBytes {
		return "", nil, fmt.Errorf("%w: secret < 32 bytes (HMAC strength insufficient)", ErrScopedAuthInvalid)
	}
	now := time.Now
	if input.NowFunc != nil {
		now = input.NowFunc
	}
	idFn := NewULID
	if input.IDFunc != nil {
		idFn = input.IDFunc
	}

	maxUses := input.MaxUses
	if maxUses < 0 {
		return "", nil, fmt.Errorf("%w: max_uses must be >= 0", ErrScopedAuthInvalid)
	}
	if maxUses == 0 {
		maxUses = 1
	}

	issuedAt := now()
	sa := &ScopedAuthorization{
		ID:             idFn(),
		Format:         scopedAuthFormat,
		PrincipalID:    input.Principal.ID,
		PrincipalKind:  input.Principal.Kind,
		PrincipalOrgID: input.Principal.OrgID,
		Action:         input.Action,
		Resource:       input.Resource,
		IssuedAtUnix:   issuedAt.Unix(),
		ExpiresAtUnix:  issuedAt.Add(input.TTL).Unix(),
		MaxUses:        maxUses,
		AudienceID:     input.AudienceID,
		CatalogDigest:  input.CatalogDigest,
		RequestDigest:  input.RequestDigest,
		Caveats:        input.Caveats,
	}

	envelope, err := json.Marshal(sa)
	if err != nil {
		return "", nil, fmt.Errorf("%w: marshal: %v", ErrScopedAuthInvalid, err)
	}
	signature := hmacSHA256(envelope, secret)
	encoded := base64.RawURLEncoding.EncodeToString(envelope) + "." +
		base64.RawURLEncoding.EncodeToString(signature)
	return encoded, sa, nil
}

// =====================================================================
// Verify (plugin-side)
// =====================================================================

// VerifyExpectations is what the verifier checks the token's
// claims against. Empty fields skip the corresponding check.
//
// **The verifier is the contract enforcer.** A token's claims are
// just JSON until the verifier matches them against runtime
// reality. Skipping a check (leaving an Expect* field empty) is
// a security choice the caller makes; document yours.
type VerifyExpectations struct {
	// Action: the actual call's action. Token must declare
	// the SAME action; mismatch → reject.
	Action string

	// Resource: the actual call's resource. When non-empty, the token's
	// Resource must match exactly; an unbound token cannot authorize a
	// resource-specific call. Empty Expectations.Resource skips the check.
	Resource string

	// Audience: the verifying plugin's canonical identity. When non-empty,
	// the token's AudienceID must match exactly; an empty token audience is
	// not a wildcard. Empty Expectations.Audience skips the low-level check.
	Audience string

	// CatalogDigest and RequestDigest require exact non-empty token matches
	// when populated by a host-side session.
	CatalogDigest string
	RequestDigest string

	// PrincipalID: the principal stamped on the request ctx.
	// Token's PrincipalID must match. Empty skips check.
	PrincipalID string

	// PrincipalKind and OrganizationID bind the remaining trusted principal
	// dimensions. Empty skips the corresponding low-level check.
	PrincipalKind  string
	OrganizationID string

	// Now: the clock the verifier uses for expiry. Empty →
	// time.Now. Tests pass an explicit clock.
	Now time.Time

	// CaveatVerifiers, when non-empty, are consulted for each
	// caveat key in the token. A caveat key not in this map
	// causes verification to FAIL (unknown caveats are denied
	// — security default; an attacker could try to encode a
	// caveat the verifier doesn't understand).
	CaveatVerifiers map[string]CaveatVerifier

	// RequiredCaveats lists caveats the verifier expects the token to carry.
	// Registering a verifier alone only constrains a caveat when present; this
	// field prevents omission from weakening a tenant/resource/budget binding.
	RequiredCaveats []string
}

// CaveatVerifier checks a single caveat against the call context.
// Return nil to accept; return error (with reason) to reject.
type CaveatVerifier func(value any) error

// Verify decodes + validates the token against expectations and
// the secret. Returns the decoded ScopedAuthorization on success.
//
// Failure modes (all wrap ErrScopedAuthInvalid):
//   - decode fails (bad base64, bad JSON, missing parts)
//   - format tag unrecognized (forward-compat: future versions
//     will dispatch on Format and call a different verifier)
//   - HMAC mismatch (tampered or wrong secret)
//   - expired (now > ExpiresAt + skew)
//   - audience/action/resource/principal mismatch
//   - unknown caveat key
//   - registered caveat verifier rejected
func Verify(token string, expect VerifyExpectations, secret []byte) (*ScopedAuthorization, error) {
	if token == "" {
		return nil, fmt.Errorf("%w: empty token", ErrScopedAuthInvalid)
	}
	if len(secret) < MinScopedAuthSecretBytes {
		return nil, fmt.Errorf("%w: verifier secret < 32 bytes", ErrScopedAuthInvalid)
	}

	// Split <envelope>.<signature>.
	dot := strings.IndexByte(token, '.')
	if dot < 0 || dot == len(token)-1 {
		return nil, fmt.Errorf("%w: malformed token (expected <envelope>.<sig>)", ErrScopedAuthInvalid)
	}
	envB64, sigB64 := token[:dot], token[dot+1:]

	envelope, err := base64.RawURLEncoding.DecodeString(envB64)
	if err != nil {
		return nil, fmt.Errorf("%w: envelope base64: %v", ErrScopedAuthInvalid, err)
	}
	sig, err := base64.RawURLEncoding.DecodeString(sigB64)
	if err != nil {
		return nil, fmt.Errorf("%w: sig base64: %v", ErrScopedAuthInvalid, err)
	}

	// Constant-time HMAC compare. hmac.Equal handles the timing
	// safely; defense against signature-comparison side channels.
	expected := hmacSHA256(envelope, secret)
	if !hmac.Equal(sig, expected) {
		return nil, fmt.Errorf("%w: signature mismatch (tampered or wrong secret)", ErrScopedAuthInvalid)
	}

	var sa ScopedAuthorization
	if err := json.Unmarshal(envelope, &sa); err != nil {
		return nil, fmt.Errorf("%w: envelope json: %v", ErrScopedAuthInvalid, err)
	}

	if sa.Format != scopedAuthFormat {
		return nil, fmt.Errorf("%w: Verify (HMAC) received fmt=%q (expected %q); use TokenVerifier for dual-format dispatch",
			ErrScopedAuthInvalid, sa.Format, scopedAuthFormat)
	}

	if err := checkScopedAuthClaims(&sa, expect); err != nil {
		return nil, err
	}
	return &sa, nil
}

// hmacSHA256 computes HMAC-SHA256 of message with key.
func hmacSHA256(message, key []byte) []byte {
	mac := hmac.New(sha256.New, key)
	mac.Write(message)
	return mac.Sum(nil)
}

// =====================================================================
// Replay tracking (plugin-side)
// =====================================================================

// ReplayTracker records token consumption to enforce MaxUses.
// Plugin holds one of these per Guard. Tracker doesn't survive
// process restart — that's acceptable: tokens expire in seconds,
// so a restart-induced replay window is bounded by the token's
// own expiry.
//
// Implementation: in-memory map keyed by token ID. Entries are
// pruned lazily — we don't run a background sweeper because
// tokens self-expire within seconds.
type ReplayTracker struct {
	mu    sync.Mutex
	uses  map[string]*replayEntry
	clock func() time.Time
}

type replayEntry struct {
	count     int
	expiresAt time.Time
}

// NewReplayTracker constructs an empty tracker.
func NewReplayTracker() *ReplayTracker {
	return &ReplayTracker{
		uses:  make(map[string]*replayEntry),
		clock: time.Now,
	}
}

// Consume reserves one use of the token. Returns
// ErrScopedAuthExhausted if max_uses has been consumed already.
// Lazily prunes expired entries on each call.
func (r *ReplayTracker) Consume(sa *ScopedAuthorization) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	now := r.clock()
	r.pruneLocked(now)

	expiresAt := time.Unix(sa.ExpiresAtUnix, 0).Add(scopedAuthClockSkew)
	entry, ok := r.uses[sa.ID]
	if !ok {
		entry = &replayEntry{expiresAt: expiresAt}
		r.uses[sa.ID] = entry
	}
	entry.count++
	if entry.count > sa.MaxUses {
		return ErrScopedAuthExhausted
	}
	return nil
}

// pruneLocked sweeps entries past their expiry. Called under r.mu.
// O(n) — fine because n is bounded by the rate of tokens minted,
// which is rate-limited at the gateway.
func (r *ReplayTracker) pruneLocked(now time.Time) {
	for id, entry := range r.uses {
		if now.After(entry.expiresAt) {
			delete(r.uses, id)
		}
	}
}

// Size returns the number of tracked tokens. Used by tests.
func (r *ReplayTracker) Size() int {
	r.mu.Lock()
	defer r.mu.Unlock()
	return len(r.uses)
}

// =====================================================================
// Context plumbing
// =====================================================================

type scopedAuthCtxKey struct{}

// WithScopedAuth stamps a verified ScopedAuthorization on ctx.
// Called by the Guard after successful Verify; handlers can read
// via ScopedAuthFrom for audit logging.
func WithScopedAuth(ctx context.Context, sa *ScopedAuthorization) context.Context {
	if ctx == nil {
		ctx = context.Background()
	}
	return context.WithValue(ctx, scopedAuthCtxKey{}, sa)
}

// ScopedAuthFrom returns the ScopedAuthorization stamped on ctx,
// or nil if none. Plugin handlers can read this for audit
// logging — show the token id alongside other request context.
//
// Handlers SHOULD NOT make authorization decisions based on the
// presence of a token; the Guard already gated the call.
func ScopedAuthFrom(ctx context.Context) *ScopedAuthorization {
	if ctx == nil {
		return nil
	}
	sa, _ := ctx.Value(scopedAuthCtxKey{}).(*ScopedAuthorization)
	return sa
}

// =====================================================================
// Metadata header helpers
// =====================================================================

// ScopedAuthMetadataKey is the gRPC metadata header that carries
// the encoded token. Lowercase per gRPC convention.
const ScopedAuthMetadataKey = "x-codefly-scoped-authz"

// =====================================================================
// Secret generation
// =====================================================================

// NewSpawnSecret returns a 32-byte cryptographically random
// secret suitable for HMAC-SHA256. Used by manager.Load to mint
// a per-spawn signing key shared with the plugin.
//
// Panics on rand source failure — that's an unrecoverable system
// issue, not something to swallow.
func NewSpawnSecret() []byte {
	buf := make([]byte, MinScopedAuthSecretBytes)
	if _, err := rand.Read(buf); err != nil {
		panic(fmt.Sprintf("policy: crypto/rand failure: %v", err))
	}
	return buf
}

// =====================================================================
// ULID — minimal in-package implementation
// =====================================================================

// NewULID returns a time-prefixed, base32-encoded random identifier
// suitable for token IDs.
//
// **Why not a strict-spec ULID.** The proposal called for ULIDs for
// time-ordered audit scans. For our purposes (token IDs that need
// to be unique and ideally sortable), a hex-encoded
// `<unix-millis>-<random>` is simpler and adequate:
//
//   - Unique enough: 64 bits of random per ID, collision-free at
//     codefly's scale.
//   - Time-sortable: hex-encoded millis prefix sorts correctly
//     (until year 5138; we're not worried).
//   - URL-safe: hex characters fit any header / log format.
//   - 24 chars fixed-width: 16 (millis) + 1 (separator) + 16 (random).
//
// If we ever need strict-spec ULIDs (e.g. for cross-system
// correlation with another service that mints ULIDs), import
// github.com/oklog/ulid; for now this is dependency-free.
func NewULID() string {
	ms := time.Now().UnixMilli()
	var entropy [8]byte
	if _, err := rand.Read(entropy[:]); err != nil {
		panic(fmt.Sprintf("policy: crypto/rand failure in NewULID: %v", err))
	}
	return fmt.Sprintf("%016x-%016x", ms, binary.BigEndian.Uint64(entropy[:]))
}
