# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/agent/agent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aservices/agent/agent.proto\x12\x11v1.services.agent\"s\n\nCapability\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32\".v1.services.agent.Capability.TypeR\x04type\"-\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x46\x41\x43TORY\x10\x01\x12\x0b\n\x07RUNTIME\x10\x02\"U\n\x10\x41gentInformation\x12\x41\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0b\x32\x1d.v1.services.agent.CapabilityR\x0c\x63\x61pabilities\"\x19\n\x17\x41gentInformationRequest2q\n\x05\x41gent\x12h\n\x13GetAgentInformation\x12*.v1.services.agent.AgentInformationRequest\x1a#.v1.services.agent.AgentInformation\"\x00\x42\xc1\x01\n\x15\x63om.v1.services.agentB\nAgentProtoP\x01Z6github.com/codefly-dev/core/proto/v1/go/services/agent\xa2\x02\x03VSA\xaa\x02\x11V1.Services.Agent\xca\x02\x11V1\\Services\\Agent\xe2\x02\x1dV1\\Services\\Agent\\GPBMetadata\xea\x02\x13V1::Services::Agentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.agent.agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.v1.services.agentB\nAgentProtoP\001Z6github.com/codefly-dev/core/proto/v1/go/services/agent\242\002\003VSA\252\002\021V1.Services.Agent\312\002\021V1\\Services\\Agent\342\002\035V1\\Services\\Agent\\GPBMetadata\352\002\023V1::Services::Agent'
  _globals['_CAPABILITY']._serialized_start=49
  _globals['_CAPABILITY']._serialized_end=164
  _globals['_CAPABILITY_TYPE']._serialized_start=119
  _globals['_CAPABILITY_TYPE']._serialized_end=164
  _globals['_AGENTINFORMATION']._serialized_start=166
  _globals['_AGENTINFORMATION']._serialized_end=251
  _globals['_AGENTINFORMATIONREQUEST']._serialized_start=253
  _globals['_AGENTINFORMATIONREQUEST']._serialized_end=278
  _globals['_AGENT']._serialized_start=280
  _globals['_AGENT']._serialized_end=393
# @@protoc_insertion_point(module_scope)
