package main

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// options carries the facade-specific plugin parameters:
//
//	services=A+B         restrict output to the listed services (unknown → error)
//	module=<name>        override the entry-point/file name (single package only)
//	fail_on_streaming    turn the skipped-streaming-RPC comment into an error
type options struct {
	services         map[string]bool
	module           string
	failOnStreaming  bool
	servicesRequests []string
}

// parseParams splits the comma-separated protoc parameter string, extracting
// the facade options and returning the remaining parameters (e.g.
// paths=source_relative) unchanged for protogen to consume.
func parseParams(param string) (options, string) {
	var opts options
	var kept []string
	for _, item := range strings.Split(param, ",") {
		if item == "" {
			continue
		}
		key, value, _ := strings.Cut(item, "=")
		switch strings.TrimSpace(key) {
		case "services":
			opts.services = map[string]bool{}
			for _, s := range strings.Split(value, "+") {
				if s = strings.TrimSpace(s); s != "" {
					opts.services[s] = true
					opts.servicesRequests = append(opts.servicesRequests, s)
				}
			}
		case "module":
			opts.module = strings.TrimSpace(value)
		case "fail_on_streaming":
			opts.failOnStreaming = strings.TrimSpace(value) == "true"
		default:
			kept = append(kept, item)
		}
	}
	return opts, strings.Join(kept, ",")
}

// packageGroup is the set of target files sharing one proto package. A
// service's fully-qualified name — hence its facade — is per package, so each
// package gets its own file.
type packageGroup struct {
	protoPackage string
	files        []*protogen.File
	services     []*protogen.Service
}

func generate(gen *protogen.Plugin, opts options) error {
	groups, err := collect(gen, opts)
	if err != nil {
		return err
	}

	if len(opts.services) > 0 {
		available := map[string]bool{}
		for _, g := range groups {
			for _, s := range g.services {
				available[string(s.Desc.Name())] = true
			}
		}
		var unknown []string
		for _, s := range opts.servicesRequests {
			if !available[s] {
				unknown = append(unknown, s)
			}
		}
		if len(unknown) > 0 {
			return fmt.Errorf("declared services not found in the proto: %v", unknown)
		}
	}

	moduleNames := map[string]string{}
	for _, g := range groups {
		module := defaultModuleName(g.protoPackage)
		if opts.module != "" && len(groups) == 1 {
			module = opts.module
		}
		if other, ok := moduleNames[module]; ok {
			return fmt.Errorf("module name collision: packages %s and %s both map to %s", g.protoPackage, other, module)
		}
		moduleNames[module] = g.protoPackage
		if err := emit(gen, g, module, opts); err != nil {
			return err
		}
	}
	return nil
}

// collect groups the services in the generated files by proto package,
// applying the services= filter.
func collect(gen *protogen.Plugin, opts options) ([]*packageGroup, error) {
	byPackage := map[string]*packageGroup{}
	var order []string
	for _, f := range gen.Files {
		if !f.Generate || len(f.Services) == 0 {
			continue
		}
		pkg := string(f.Desc.Package())
		g, ok := byPackage[pkg]
		if !ok {
			g = &packageGroup{protoPackage: pkg}
			byPackage[pkg] = g
			order = append(order, pkg)
		}
		g.files = append(g.files, f)
		for _, s := range f.Services {
			if len(opts.services) > 0 && !opts.services[string(s.Desc.Name())] {
				continue
			}
			g.services = append(g.services, s)
		}
	}
	var groups []*packageGroup
	for _, pkg := range order {
		if len(byPackage[pkg].services) > 0 {
			groups = append(groups, byPackage[pkg])
		}
	}
	return groups, nil
}

func emit(gen *protogen.Plugin, g *packageGroup, module string, opts options) error {
	head := g.files[0]
	connectImport := protogen.GoImportPath(string(head.GoImportPath) + "/" + string(head.GoPackageName) + "connect")

	// The facade lives in its own package (a <module>/ subdirectory of the
	// message package) rather than the message package itself: the connect
	// stubs already import the message package, so a facade there would close
	// an import cycle. Its own package also gives the intended `<module>.New(gw)`
	// entry point.
	facadeImport := protogen.GoImportPath(string(head.GoImportPath) + "/" + module)
	filename := path.Join(path.Dir(head.GeneratedFilenamePrefix), module, module+"_facade.pb.go")
	gf := gen.NewGeneratedFile(filename, facadeImport)

	connectQual := func(name string) string {
		return gf.QualifiedGoIdent(connectImport.Ident(name))
	}
	connectPkg := connectQual("New") // force the import + resolve its alias
	connectPkg = connectPkg[:strings.LastIndex(connectPkg, ".")]

	gf.P("// generated by protoc-gen-codefly-facade-go from ", g.protoPackage, "; do not edit")
	gf.P()
	gf.P("package ", module)
	gf.P()

	httpClient := gf.QualifiedGoIdent(protogen.GoImportPath("net/http").Ident("Client"))
	connectImportName := gf.QualifiedGoIdent(protogen.GoImportPath("connectrpc.com/connect").Ident("ClientOption"))
	connectImportName = connectImportName[:strings.LastIndex(connectImportName, ".")]

	gf.P("// Gateway is the minimal surface this facade needs from the solution runtime.")
	gf.P("type Gateway interface {")
	gf.P("\tBaseURL() string")
	gf.P("\tHTTPClient() *", httpClient)
	gf.P("}")
	gf.P()
	gf.P("// Client is the entry point: New(gw).<Service>().<Rpc>(ctx, req).")
	gf.P("type Client struct {")
	gf.P("\tgw   Gateway")
	gf.P("\topts []", connectImportName, ".ClientOption")
	gf.P("}")
	gf.P()
	gf.P("// New binds the facade to a gateway. Extra connect.ClientOptions are")
	gf.P("// forwarded to every sub-client.")
	gf.P("func New(gw Gateway, opts ...", connectImportName, ".ClientOption) *Client {")
	gf.P("\treturn &Client{gw: gw, opts: opts}")
	gf.P("}")
	gf.P()

	wrapperNames := map[string]string{}
	accessorNames := map[string]bool{}
	for _, s := range g.services {
		accessor := accessorName(string(s.GoName))
		wrapper := wrapperName(accessor)
		if other, ok := wrapperNames[wrapper]; ok {
			return fmt.Errorf("service class collision: %s and %s both map to %s", s.GoName, other, wrapper)
		}
		wrapperNames[wrapper] = string(s.GoName)
		if accessorNames[accessor] {
			return fmt.Errorf("service accessor collision: %s maps to an accessor already in use (%s)", s.GoName, accessor)
		}
		accessorNames[accessor] = true

		clientIface := connectQual(string(s.GoName) + "Client")
		newClient := connectPkg + ".New" + string(s.GoName) + "Client"

		gf.P("// ", accessor, " returns the typed ", s.GoName, " facade.")
		gf.P("func (c *Client) ", accessor, "() *", wrapper, " {")
		gf.P("\treturn &", wrapper, "{inner: ", newClient, "(c.gw.HTTPClient(), c.gw.BaseURL(), c.opts...)}")
		gf.P("}")
		gf.P()
		gf.P("// ", wrapper, " wraps the generated ", s.GoName, "Client and hides the")
		gf.P("// connect.Request/Response envelope.")
		gf.P("type ", wrapper, " struct {")
		gf.P("\tinner ", clientIface)
		gf.P("}")
		gf.P()

		methodNames := map[string]string{}
		for _, m := range s.Methods {
			method := string(m.GoName)
			if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
				if opts.failOnStreaming {
					return fmt.Errorf("streaming RPC %s.%s: facades do not support streaming (fail_on_streaming=true)", s.GoName, method)
				}
				gf.P("// skipped: streaming RPC ", method)
				gf.P()
				continue
			}
			if other, ok := methodNames[method]; ok {
				return fmt.Errorf("method name collision in %s: %s and %s both map to %s", s.GoName, m.GoName, other, method)
			}
			methodNames[method] = string(m.GoName)
			// Resolved here, not once up top: a service with only streaming
			// (skipped) RPCs emits no method, and importing context/NewRequest
			// then would leave them unused and the file uncompilable.
			ctxType := gf.QualifiedGoIdent(protogen.GoImportPath("context").Ident("Context"))
			newRequest := gf.QualifiedGoIdent(protogen.GoImportPath("connectrpc.com/connect").Ident("NewRequest"))
			req := gf.QualifiedGoIdent(m.Input.GoIdent)
			resp := gf.QualifiedGoIdent(m.Output.GoIdent)
			gf.P("func (a *", wrapper, ") ", method, "(ctx ", ctxType, ", req *", req, ") (*", resp, ", error) {")
			gf.P("\tresp, err := a.inner.", method, "(ctx, ", newRequest, "(req))")
			gf.P("\tif err != nil {")
			gf.P("\t\treturn nil, err")
			gf.P("\t}")
			gf.P("\treturn resp.Msg, nil")
			gf.P("}")
			gf.P()
		}
	}
	return nil
}

func accessorName(serviceGoName string) string {
	return strings.TrimSuffix(serviceGoName, "Service")
}

func wrapperName(accessor string) string {
	if strings.HasSuffix(accessor, "Client") {
		return accessor
	}
	return accessor + "Client"
}

func defaultModuleName(protoPackage string) string {
	var segments []string
	for _, s := range strings.Split(protoPackage, ".") {
		if isVersionSegment(s) {
			continue
		}
		segments = append(segments, s)
	}
	if len(segments) == 0 {
		return strings.ReplaceAll(protoPackage, ".", "_")
	}
	return segments[len(segments)-1]
}

func isVersionSegment(s string) bool {
	if len(s) < 2 || s[0] != 'v' {
		return false
	}
	for _, r := range s[1:] {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}
