# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/agent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61se/agent.proto\x12\x07v1.base\"\x9e\x01\n\x05\x41gent\x12\'\n\x04kind\x18\x01 \x01(\x0e\x32\x13.v1.base.Agent.KindR\x04kind\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n\tpublisher\x18\x03 \x01(\tR\tpublisher\x12\x18\n\x07version\x18\x04 \x01(\tR\x07version\" \n\x04Kind\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVICE\x10\x01\x42\x84\x01\n\x0b\x63om.v1.baseB\nAgentProtoP\x01Z,github.com/codefly-dev/core/proto/v1/go/base\xa2\x02\x03VBX\xaa\x02\x07V1.Base\xca\x02\x07V1\\Base\xe2\x02\x13V1\\Base\\GPBMetadata\xea\x02\x08V1::Baseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base.agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.v1.baseB\nAgentProtoP\001Z,github.com/codefly-dev/core/proto/v1/go/base\242\002\003VBX\252\002\007V1.Base\312\002\007V1\\Base\342\002\023V1\\Base\\GPBMetadata\352\002\010V1::Base'
  _globals['_AGENT']._serialized_start=30
  _globals['_AGENT']._serialized_end=188
  _globals['_AGENT_KIND']._serialized_start=156
  _globals['_AGENT_KIND']._serialized_end=188
# @@protoc_insertion_point(module_scope)
