# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/organization.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x61se/organization.proto\x12\x07v1.base\x1a\x1b\x62uf/validate/validate.proto\"E\n\x0cOrganization\x12\x1d\n\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x04name\x12\x16\n\x06\x64omain\x18\x02 \x01(\tR\x06\x64omainB\x8b\x01\n\x0b\x63om.v1.baseB\x11OrganizationProtoP\x01Z,github.com/codefly-dev/core/proto/v1/go/base\xa2\x02\x03VBX\xaa\x02\x07V1.Base\xca\x02\x07V1\\Base\xe2\x02\x13V1\\Base\\GPBMetadata\xea\x02\x08V1::Baseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base.organization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.v1.baseB\021OrganizationProtoP\001Z,github.com/codefly-dev/core/proto/v1/go/base\242\002\003VBX\252\002\007V1.Base\312\002\007V1\\Base\342\002\023V1\\Base\\GPBMetadata\352\002\010V1::Base'
  _globals['_ORGANIZATION'].fields_by_name['name']._options = None
  _globals['_ORGANIZATION'].fields_by_name['name']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_ORGANIZATION']._serialized_start=65
  _globals['_ORGANIZATION']._serialized_end=134
# @@protoc_insertion_point(module_scope)
