# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions/workspace.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import organization_pb2 as base_dot_organization__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61\x63tions/workspace.proto\x12\nv1.actions\x1a\x17\x62\x61se/organization.proto\"\xc8\x01\n\x0c\x41\x64\x64Workspace\x12\x12\n\x04kind\x18\x01 \x01(\tR\x04kind\x12\x39\n\x0corganization\x18\x02 \x01(\x0b\x32\x15.v1.base.OrganizationR\x0corganization\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x04 \x01(\tR\x0b\x64\x65scription\x12\x10\n\x03\x64ir\x18\x05 \x01(\tR\x03\x64ir\x12!\n\x0cproject_root\x18\x06 \x01(\tR\x0bprojectRootB\x9a\x01\n\x0e\x63om.v1.actionsB\x0eWorkspaceProtoP\x01Z/github.com/codefly-dev/core/proto/v1/go/actions\xa2\x02\x03VAX\xaa\x02\nV1.Actions\xca\x02\nV1\\Actions\xe2\x02\x16V1\\Actions\\GPBMetadata\xea\x02\x0bV1::Actionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actions.workspace_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.v1.actionsB\016WorkspaceProtoP\001Z/github.com/codefly-dev/core/proto/v1/go/actions\242\002\003VAX\252\002\nV1.Actions\312\002\nV1\\Actions\342\002\026V1\\Actions\\GPBMetadata\352\002\013V1::Actions'
  _globals['_ADDWORKSPACE']._serialized_start=65
  _globals['_ADDWORKSPACE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
