# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: providers/provider.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18providers/provider.proto\x12\x0bv1.provider\"\r\n\x0bInitRequest\"\x0e\n\x0cInitResponse2G\n\x08Provider\x12;\n\x04Init\x12\x18.v1.provider.InitRequest\x1a\x19.v1.provider.InitResponseB\xa0\x01\n\x0f\x63om.v1.providerB\rProviderProtoP\x01Z1github.com/codefly-dev/core/proto/v1/go/providers\xa2\x02\x03VPX\xaa\x02\x0bV1.Provider\xca\x02\x0bV1\\Provider\xe2\x02\x17V1\\Provider\\GPBMetadata\xea\x02\x0cV1::Providerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'providers.provider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.v1.providerB\rProviderProtoP\001Z1github.com/codefly-dev/core/proto/v1/go/providers\242\002\003VPX\252\002\013V1.Provider\312\002\013V1\\Provider\342\002\027V1\\Provider\\GPBMetadata\352\002\014V1::Provider'
  _globals['_INITREQUEST']._serialized_start=41
  _globals['_INITREQUEST']._serialized_end=54
  _globals['_INITRESPONSE']._serialized_start=56
  _globals['_INITRESPONSE']._serialized_end=70
  _globals['_PROVIDER']._serialized_start=72
  _globals['_PROVIDER']._serialized_end=143
# @@protoc_insertion_point(module_scope)
