# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugins/logs.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import types_pb2 as base_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12plugins/logs.proto\x12\x0fv1.plugins.logs\x1a\x10\x62\x61se/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n\x03Log\x12*\n\x02\x61t\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x02\x61t\x12 \n\x0b\x61pplication\x18\x02 \x01(\tR\x0b\x61pplication\x12\x18\n\x07service\x18\x03 \x01(\tR\x07service\x12-\n\x04kind\x18\x04 \x01(\x0e\x32\x19.v1.plugins.logs.Log.KindR\x04kind\x12\x18\n\x07message\x18\x05 \x01(\tR\x07message\",\n\x04Kind\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06PLUGIN\x10\x01\x12\x0b\n\x07SERVICE\x10\x02\"g\n\x0fLogSessionGroup\x12*\n\x07session\x18\x01 \x01(\x0b\x32\x10.v1.base.SessionR\x07session\x12(\n\x04logs\x18\x02 \x03(\x0b\x32\x14.v1.plugins.logs.LogR\x04logsB\xaf\x01\n\x13\x63om.v1.plugins.logsB\tLogsProtoP\x01Z/github.com/codefly-dev/core/proto/v1/go/plugins\xa2\x02\x03VPL\xaa\x02\x0fV1.Plugins.Logs\xca\x02\x0fV1\\Plugins\\Logs\xe2\x02\x1bV1\\Plugins\\Logs\\GPBMetadata\xea\x02\x11V1::Plugins::Logsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugins.logs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.v1.plugins.logsB\tLogsProtoP\001Z/github.com/codefly-dev/core/proto/v1/go/plugins\242\002\003VPL\252\002\017V1.Plugins.Logs\312\002\017V1\\Plugins\\Logs\342\002\033V1\\Plugins\\Logs\\GPBMetadata\352\002\021V1::Plugins::Logs'
  _globals['_LOG']._serialized_start=91
  _globals['_LOG']._serialized_end=319
  _globals['_LOG_KIND']._serialized_start=275
  _globals['_LOG_KIND']._serialized_end=319
  _globals['_LOGSESSIONGROUP']._serialized_start=321
  _globals['_LOGSESSIONGROUP']._serialized_end=424
# @@protoc_insertion_point(module_scope)
