package proto

import (
	"encoding/json"
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// protocGenEsRuntimeVersion is the protoc-gen-es version the companion image
// must bake. It has to match the @bufbuild/protobuf runtime version consumers
// pin (currently 2.11.0): the generator emits the
// `// @generated by protoc-gen-es v<version>` header and codegen shaped for a
// specific runtime surface, so a companion whose es diverges from a repo's
// pinned runtime makes companion output disagree with committed *_pb.ts forever
// (sync-drift). Bump this only in lockstep with the ecosystem runtime, and only
// through docs/runbooks/bump-protobuf-es.md: the pins asserted below are four
// of the six places this version lives, and the remaining two — the flake's
// content hashes — fail the Nix build rather than any test here.
const protocGenEsRuntimeVersion = "2.11.0"

func TestCompanionInstallsLocalRustPlugins(t *testing.T) {
	for _, file := range []string{"Dockerfile", "flake.nix", "templates/rust/buf.gen.yaml.tmpl"} {
		assertMentionsAll(t, file, []string{"protoc-gen-prost", "protoc-gen-tonic"})
	}
	content, err := os.ReadFile("templates/rust/buf.gen.yaml.tmpl")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(content), "buf.build/") {
		t.Fatal("Rust generation must use the companion's local plugins")
	}
}

// bumpRunbook records why the pin sits where it does and what moving it costs.
// The guards below keep it honest, because a stale runbook is worse than none:
// it still reads as current.
const bumpRunbook = "../../docs/runbooks/bump-protobuf-es.md"

// The proto companion image has two build definitions (Dockerfile and
// flake.nix) for the same ghcr.io/codefly-dev/proto tag. Both must bake the same
// pinned es, or the image's behaviour depends on which builder published it.
var (
	protocGenEsDockerfilePin = regexp.MustCompile(`@bufbuild/protoc-gen-es@([0-9]+\.[0-9]+\.[0-9]+)`)
	protocGenEsFlakePin      = regexp.MustCompile(`protocGenEsVersion = "([0-9]+\.[0-9]+\.[0-9]+)"`)
)

// goimportsVersion is the goimports the companion bakes. The formatting pass
// is part of generation (see FormatGoOutputs), so the formatter is pinned like
// a plugin: a consumer's committed Go carries this version's shape, and a
// formatter that moved with @latest would move every checked-in tree. Both
// build definitions must bake the same one, or the image's behaviour depends on
// which builder published it.
const goimportsVersion = "0.50.0"

var (
	goimportsDockerfilePin = regexp.MustCompile(`golang\.org/x/tools/cmd/goimports@v([0-9]+\.[0-9]+\.[0-9]+)`)
	goimportsFlakePin      = regexp.MustCompile(`goimportsVersion = "([0-9]+\.[0-9]+\.[0-9]+)"`)
)

func TestDockerfilePinsGoimports(t *testing.T) {
	assertPinned(t, "Dockerfile", "goimports", goimportsDockerfilePin, goimportsVersion)
}

func TestFlakePinsGoimports(t *testing.T) {
	assertPinned(t, "flake.nix", "goimports", goimportsFlakePin, goimportsVersion)
}

// The builder stage installing goimports proves nothing about the image; only
// a COPY into the runtime stage puts it on the companion's PATH. This is the
// same shape of gap TestBuildDefinitionsInstallGrpcioToolsInRuntime guards.
func TestDockerfileShipsGoimportsInRuntime(t *testing.T) {
	dockerfile, err := os.ReadFile("Dockerfile")
	if err != nil {
		t.Fatalf("read Dockerfile: %v", err)
	}
	stages := regexp.MustCompile(`(?m)^FROM `).FindAllStringIndex(string(dockerfile), -1)
	if len(stages) < 2 {
		t.Fatalf("Dockerfile has %d FROM stages, expected the builder + runtime pair", len(stages))
	}
	runtimeStage := string(dockerfile)[stages[len(stages)-1][0]:]
	if !regexp.MustCompile(`(?m)^COPY --from=builder /go/bin/goimports /usr/local/bin/`).MatchString(runtimeStage) {
		t.Error("Dockerfile does not COPY goimports into the runtime stage; the companion would run `buf generate` and then fail its own formatting pass")
	}
	assertMentionsAll(t, "flake.nix", []string{"pinnedGoimports"})
}

// The runtime Go is not decoration: goimports names a package by running
// `go list` in the consumer's module, and a Go older than that module's
// go.mod requirement makes it refuse — after which goimports quietly formats
// syntax only and emits no alias where a package's name is not its path's
// last element. That is the committed shape, so every consumer drifts by
// exactly those lines, and nothing errors. The builder stage's Go is the
// ecosystem's; the runtime must carry that one, not whatever apk ships.
func TestDockerfileRuntimeGoIsTheBuilderToolchain(t *testing.T) {
	dockerfile, err := os.ReadFile("Dockerfile")
	if err != nil {
		t.Fatalf("read Dockerfile: %v", err)
	}
	stages := regexp.MustCompile(`(?m)^FROM `).FindAllStringIndex(string(dockerfile), -1)
	if len(stages) < 2 {
		t.Fatalf("Dockerfile has %d FROM stages, expected the builder + runtime pair", len(stages))
	}
	runtimeStage := string(dockerfile)[stages[len(stages)-1][0]:]
	if regexp.MustCompile(`(?m)^RUN apk add[^\n]*\bgo\b`).MatchString(runtimeStage) {
		t.Error("Dockerfile installs go from apk in the runtime stage; that is the base alpine's Go, older than consumers' go.mod require, and goimports then degrades silently (see the runtime-dependencies note)")
	}
	if !regexp.MustCompile(`(?m)^COPY --from=builder /usr/local/go /usr/local/go`).MatchString(runtimeStage) {
		t.Error("Dockerfile does not COPY the builder's Go toolchain into the runtime stage")
	}
	if !regexp.MustCompile(`(?m)^FROM golang:1\.27`).MatchString(string(dockerfile)) {
		t.Error("the builder stage is not golang:1.27; the runtime Go it hands the formatter would not satisfy modules that require go 1.27")
	}
	assertMentionsAll(t, "flake.nix", []string{"go_1_27"})
}

func TestDockerfilePinsProtocGenEsToRuntimeVersion(t *testing.T) {
	assertPinnedToRuntime(t, "Dockerfile", protocGenEsDockerfilePin)
}

func TestFlakePinsProtocGenEsToRuntimeVersion(t *testing.T) {
	assertPinnedToRuntime(t, "flake.nix", protocGenEsFlakePin)
}

// facadeBinaries are the plugin binaries the image must expose for facade
// generation, on top of the gRPC/OpenAPI set. protoc-gen-connect-go is what the
// Go facade imports; the three protoc-gen-codefly-facade-* binaries and
// codefly-proto-strip-options are new. Both build definitions must install
// every one, or the image's behaviour depends on which builder published it.
var facadeBinaries = []string{
	"protoc-gen-connect-go",
	"protoc-gen-codefly-facade-go",
	"protoc-gen-codefly-facade-python",
	"protoc-gen-codefly-facade-ts",
	"codefly-proto-strip-options",
}

func TestDockerfileInstallsFacadePlugins(t *testing.T) {
	assertMentionsAll(t, "Dockerfile", facadeBinaries)
	// The legacy plugin name is kept for one release so the runtime repo can
	// switch off it.
	assertMentionsAll(t, "Dockerfile", []string{"protoc-gen-solution_facade"})
}

func TestFlakeInstallsFacadePlugins(t *testing.T) {
	assertMentionsAll(t, "flake.nix", facadeBinaries)
}

// TestTsFacadePinsProtoplugin keeps the TS facade plugin's protoplugin runtime
// in lockstep with protoc-gen-es: the facade imports the service schemas es
// emits, and protoplugin ships alongside es on the same release train.
func TestTsFacadePinsProtoplugin(t *testing.T) {
	content, err := os.ReadFile("facades/ts/package.json")
	if err != nil {
		t.Fatalf("read facades/ts/package.json: %v", err)
	}
	pin := regexp.MustCompile(`"@bufbuild/protoplugin":\s*"([0-9]+\.[0-9]+\.[0-9]+)"`)
	match := pin.FindSubmatch(content)
	if match == nil {
		t.Fatal("facades/ts/package.json no longer pins @bufbuild/protoplugin to an explicit version")
	}
	if got := string(match[1]); got != protocGenEsRuntimeVersion {
		t.Fatalf("facades/ts pins @bufbuild/protoplugin %s, but the ecosystem runtime is %s", got, protocGenEsRuntimeVersion)
	}
}

// TestBuildDefinitionsInstallGrpcioToolsInRuntime guards the Python protobuf
// generator inside the image. grpc_tools is not a plugin binary that
// assertMentionsAll would catch: it is a Python module, reached as
// `python -m grpc_tools.protoc`, and a consumer generating Python stubs from a
// contract has no other way to produce them.
//
// The Dockerfile mentions grpcio-tools twice and only one of them counts. The
// builder stage installs it into a venv that is never COPYed; the runtime stage
// builds its own /venv. So the image can carry a /venv that exists, answers to
// /venv/bin/python, and still has no grpc_tools — which is what shipped in
// 0.0.14. Asserting on the runtime install specifically, rather than on the
// string appearing anywhere in the file, is the difference between this test
// passing and meaning it.
func TestBuildDefinitionsInstallGrpcioToolsInRuntime(t *testing.T) {
	dockerfile, err := os.ReadFile("Dockerfile")
	if err != nil {
		t.Fatalf("read Dockerfile: %v", err)
	}
	// Scope to the runtime stage: the builder installs grpcio-tools too, on a
	// line of the same shape, into a venv that is never copied. Matching the
	// whole file would pass on an image that ships no grpc_tools at all.
	stages := regexp.MustCompile(`(?m)^FROM `).FindAllStringIndex(string(dockerfile), -1)
	if len(stages) < 2 {
		t.Fatalf("Dockerfile has %d FROM stages, expected the builder + runtime pair; this guard can no longer tell them apart", len(stages))
	}
	runtimeStage := string(dockerfile)[stages[len(stages)-1][0]:]
	runtimeInstall := regexp.MustCompile(`/venv/bin/pip install[^\n]*\bgrpcio-tools\b`)
	if !runtimeInstall.MatchString(runtimeStage) {
		t.Error("Dockerfile does not install grpcio-tools into the RUNTIME /venv; `python -m grpc_tools.protoc` will not exist in the image even though the builder stage installs it into a venv that is never COPYed (this is what shipped in 0.0.14)")
	}

	flake, err := os.ReadFile("flake.nix")
	if err != nil {
		t.Fatalf("read flake.nix: %v", err)
	}
	// Both build definitions publish the same tag, so the facade python must
	// carry the same module.
	facadePython := regexp.MustCompile(`python3\.withPackages \(ps: \[[^\]]*\bps\.grpcio-tools\b[^\]]*\]\)`)
	if !facadePython.Match(flake) {
		t.Error("flake.nix does not give the facade python grpcio-tools; the nix-built image would lack grpc_tools while the Docker-built one has it, so behaviour would depend on which builder published the tag")
	}
}

func assertMentionsAll(t *testing.T, file string, needles []string) {
	t.Helper()
	content, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read %s: %v", file, err)
	}
	for _, needle := range needles {
		if !strings.Contains(string(content), needle) {
			t.Errorf("%s does not install %q", file, needle)
		}
	}
}

func assertPinned(t *testing.T, file, tool string, pin *regexp.Regexp, want string) {
	t.Helper()
	content, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read %s: %v", file, err)
	}
	match := pin.FindSubmatch(content)
	if match == nil {
		t.Fatalf("%s no longer pins %s to an explicit version", file, tool)
	}
	if got := string(match[1]); got != want {
		t.Fatalf("%s pins %s %s, but the companion contract is %s; the two build definitions and this constant must move together", file, tool, got, want)
	}
}

func assertPinnedToRuntime(t *testing.T, file string, pin *regexp.Regexp) {
	t.Helper()
	content, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read %s: %v", file, err)
	}
	match := pin.FindSubmatch(content)
	if match == nil {
		t.Fatalf("%s no longer pins protoc-gen-es to an explicit version", file)
	}
	if got := string(match[1]); got != protocGenEsRuntimeVersion {
		t.Fatalf("%s pins protoc-gen-es %s, but the ecosystem runtime is %s; the generator and runtime must move together (see issue #83)", file, got, protocGenEsRuntimeVersion)
	}
}

// TestBumpRunbookNamesTheCurrentPin keeps the runbook from going stale the way
// a comment does. It is the only place that records WHY the pin sits where it
// does and what moving it costs — including the flake's two content hashes,
// which nothing else checks — so a bump that leaves it describing the old
// version sends the next person through a procedure aimed at the wrong one.
func TestBumpRunbookNamesTheCurrentPin(t *testing.T) {
	content, err := os.ReadFile(bumpRunbook)
	if err != nil {
		t.Fatalf("read %s: %v", bumpRunbook, err)
	}
	// Anchored on the decision heading rather than on the version appearing
	// anywhere in the file. The runbook legitimately names older versions when
	// it recounts #83, so a bare substring check goes green on a document whose
	// stated decision is stale — which is the one thing this guard exists to
	// catch.
	heading := regexp.MustCompile(`(?m)^## Current decision: stay on ([0-9]+\.[0-9]+\.[0-9]+)$`)
	match := heading.FindSubmatch(content)
	if match == nil {
		t.Fatalf("%s has no `## Current decision: stay on <version>` heading; that heading is what this guard reads", bumpRunbook)
	}
	if got := string(match[1]); got != protocGenEsRuntimeVersion {
		t.Errorf("%s records the decision as %s, but the companion pins %s; the runbook documents a pin that moved", bumpRunbook, got, protocGenEsRuntimeVersion)
	}
}

// TestTsFacadeLockfileMatchesTheRuntime closes the one pin nothing else read.
// TestTsFacadePinsProtoplugin asserts package.json, but the Dockerfile builds
// the facade with `npm ci`, which installs from package-lock.json and ignores
// what package.json asks for. A lockfile that disagrees — a hand edit, a
// half-applied revert, a regenerated closure whose protobuf moved — therefore
// ships a protoplugin every other guard in this file believes is something
// else, and nothing fails until the image is built.
func TestTsFacadeLockfileMatchesTheRuntime(t *testing.T) {
	const lockfile = "facades/ts/package-lock.json"
	content, err := os.ReadFile(lockfile)
	if err != nil {
		t.Fatalf("read %s: %v", lockfile, err)
	}
	var lock struct {
		Packages map[string]struct {
			Version      string            `json:"version"`
			Dependencies map[string]string `json:"dependencies"`
		} `json:"packages"`
	}
	if err = json.Unmarshal(content, &lock); err != nil {
		t.Fatalf("parse %s: %v", lockfile, err)
	}
	root, ok := lock.Packages[""]
	if !ok {
		t.Fatalf("%s has no root package entry; the lockfile changed shape and this guard can no longer read it", lockfile)
	}
	if got := root.Dependencies["@bufbuild/protoplugin"]; got != protocGenEsRuntimeVersion {
		t.Errorf("%s declares @bufbuild/protoplugin %q at its root, but the ecosystem runtime is %s; package.json and the lockfile disagree, and `npm ci` installs the lockfile", lockfile, got, protocGenEsRuntimeVersion)
	}
	// The resolved entries are what npm ci actually unpacks. protoplugin pins
	// its protobuf exactly, so both sit on the runtime version.
	for _, pkg := range []string{"node_modules/@bufbuild/protoplugin", "node_modules/@bufbuild/protobuf"} {
		entry, ok := lock.Packages[pkg]
		if !ok {
			t.Errorf("%s resolves no %s; the facade plugin cannot build without it", lockfile, pkg)
			continue
		}
		if entry.Version != protocGenEsRuntimeVersion {
			t.Errorf("%s resolves %s to %s, but the ecosystem runtime is %s", lockfile, pkg, entry.Version, protocGenEsRuntimeVersion)
		}
	}
}

// runbookCitations maps each `<file>:<line>` the runbook cites to a substring
// that line must contain. A citation is useful only while it points at what it
// names, and inserting a line anywhere above one silently re-aims it at a
// neighbour — the reader then checks the wrong line, finds something plausible,
// and moves on.
var runbookCitations = map[string]string{
	"Dockerfile:98": "@bufbuild/protoc-gen-es@",
	"flake.nix:51":  "protocGenEsVersion =",
	"flake.nix:59":  "hash =",
	"flake.nix:61":  "npmDepsHash =",
}

func TestRunbookCitationsPointAtWhatTheyName(t *testing.T) {
	content, err := os.ReadFile(bumpRunbook)
	if err != nil {
		t.Fatalf("read %s: %v", bumpRunbook, err)
	}
	cites := regexp.MustCompile(`companions/proto/([A-Za-z0-9_.-]+):([0-9]+)`).FindAllStringSubmatch(string(content), -1)
	if len(cites) == 0 {
		t.Fatalf("%s cites no companions/proto <file>:<line> at all; the table changed shape and this guard can no longer find them", bumpRunbook)
	}
	seen := make(map[string]bool, len(cites))
	for _, cite := range cites {
		key := cite[1] + ":" + cite[2]
		if seen[key] {
			continue
		}
		seen[key] = true
		want, registered := runbookCitations[key]
		if !registered {
			t.Errorf("%s cites %s, which this guard does not know about; add it to runbookCitations so the citation stays verified", bumpRunbook, key)
			continue
		}
		number, err := strconv.Atoi(cite[2])
		if err != nil {
			t.Errorf("%s cites a non-numeric line in %s", bumpRunbook, key)
			continue
		}
		file, err := os.ReadFile(cite[1])
		if err != nil {
			t.Errorf("%s cites %s, which cannot be read: %v", bumpRunbook, key, err)
			continue
		}
		lines := strings.Split(string(file), "\n")
		if number < 1 || number > len(lines) {
			t.Errorf("%s cites %s, but that file has %d lines", bumpRunbook, key, len(lines))
			continue
		}
		if got := lines[number-1]; !strings.Contains(got, want) {
			t.Errorf("%s cites %s for %q, but that line reads %q; an edit shifted it and the runbook now misdirects the reader", bumpRunbook, key, want, strings.TrimSpace(got))
		}
	}
	for key := range runbookCitations {
		if !seen[key] {
			t.Errorf("%s no longer cites %s; drop it from runbookCitations or restore the citation", bumpRunbook, key)
		}
	}
}

// TestTypeScriptTemplateUsesTheBakedProtocGenEs keeps the generator a consumer's
// bindings come from inside the guarantee the rest of this file makes. A
// remotely-resolved es entry is a second pin that nothing holds to
// protocGenEsRuntimeVersion — the template generated with v2.2.3 for as long as
// the image baked 2.11.0 — and it is resolved over the network, so generation
// depends on the BSR being reachable and under its rate limit.
//
// The template is version v2, where the baked plugin is `local: protoc-gen-es`
// and a remote one is `remote:` rather than v1's `name:` and `plugin:`. Both
// remote spellings are rejected: the format changed, the reason did not.
func TestTypeScriptTemplateUsesTheBakedProtocGenEs(t *testing.T) {
	content, err := os.ReadFile("templates/typescript/buf.gen.yaml.tmpl")
	if err != nil {
		t.Fatalf("read templates/typescript/buf.gen.yaml.tmpl: %v", err)
	}
	if match := regexp.MustCompile(`(?:plugin|remote):\s*buf\.build/bufbuild/es\S*`).Find(content); match != nil {
		t.Errorf("the TypeScript template resolves es remotely (%s); use the image's own `local: protoc-gen-es`, which companion_plugins_test.go pins to %s", match, protocGenEsRuntimeVersion)
	}
	if !regexp.MustCompile(`(?m)^\s*-\s*local:\s*protoc-gen-es\s*$`).Match(content) {
		t.Error("the TypeScript template no longer runs the image's own protoc-gen-es")
	}
}
