package proto

import (
	"os"
	"regexp"
	"testing"
)

// protocGenEsRuntimeVersion is the protoc-gen-es version the companion image
// must bake. It has to match the @bufbuild/protobuf runtime version consumers
// pin (currently 2.11.0): the generator emits the
// `// @generated by protoc-gen-es v<version>` header and codegen shaped for a
// specific runtime surface, so a companion whose es diverges from a repo's
// pinned runtime makes companion output disagree with committed *_pb.ts forever
// (sync-drift). Bump this only in lockstep with the ecosystem runtime.
const protocGenEsRuntimeVersion = "2.11.0"

// The proto companion image has two build definitions (Dockerfile and
// flake.nix) for the same codeflydev/proto tag. Both must bake the same
// pinned es, or the image's behaviour depends on which builder published it.
var (
	protocGenEsDockerfilePin = regexp.MustCompile(`@bufbuild/protoc-gen-es@([0-9]+\.[0-9]+\.[0-9]+)`)
	protocGenEsFlakePin      = regexp.MustCompile(`protocGenEsVersion = "([0-9]+\.[0-9]+\.[0-9]+)"`)
)

func TestDockerfilePinsProtocGenEsToRuntimeVersion(t *testing.T) {
	assertPinnedToRuntime(t, "Dockerfile", protocGenEsDockerfilePin)
}

func TestFlakePinsProtocGenEsToRuntimeVersion(t *testing.T) {
	assertPinnedToRuntime(t, "flake.nix", protocGenEsFlakePin)
}

func assertPinnedToRuntime(t *testing.T, file string, pin *regexp.Regexp) {
	t.Helper()
	content, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read %s: %v", file, err)
	}
	match := pin.FindSubmatch(content)
	if match == nil {
		t.Fatalf("%s no longer pins protoc-gen-es to an explicit version", file)
	}
	if got := string(match[1]); got != protocGenEsRuntimeVersion {
		t.Fatalf("%s pins protoc-gen-es %s, but the ecosystem runtime is %s; the generator and runtime must move together (see issue #83)", file, got, protocGenEsRuntimeVersion)
	}
}
