//go:build proto_companion_required

package proto_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"github.com/codefly-dev/core/resources"
	"github.com/codefly-dev/core/runners/companion"
	"github.com/codefly-dev/core/wool"

	"github.com/codefly-dev/core/companions/proto"
	"github.com/codefly-dev/core/companions/testutil"
	"github.com/codefly-dev/core/languages"
	"github.com/codefly-dev/core/shared"
	"github.com/stretchr/testify/require"
)

// testdataDir returns the path to companions/proto/testdata (works from any cwd).
func testdataDir(t *testing.T) string {
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Join(filepath.Dir(filename), "testdata")
	abs, err := filepath.Abs(dir)
	require.NoError(t, err)
	return abs
}

func TestGenerateGoGRPC(t *testing.T) {
	wool.SetGlobalLogLevel(wool.DEBUG)
	ctx := context.Background()

	testutil.RequireProtoImage(t, ctx)

	apiProto := filepath.Join(testdataDir(t), "api.proto")
	ep := &resources.Endpoint{Module: "app", Service: "svc", Name: "api", Visibility: "private"}
	api, err := resources.LoadGrpcAPI(ctx, shared.Pointer(apiProto))
	require.NoError(t, err)
	grpc, err := resources.NewAPI(ctx, ep, resources.ToGrpcAPI(api))
	require.NoError(t, err)
	destination := t.TempDir()

	err = proto.GenerateGRPC(ctx, languages.GO, destination, "app/svc", grpc)
	require.NoError(t, err, "proto companion image not built: %s", testutil.BuildCompanionsHint)

	for _, name := range []string{"app_svc_api.pb.go", "app_svc_api_grpc.pb.go"} {
		require.FileExists(t, filepath.Join(destination, name))
	}
	img, err := proto.CompanionImage(ctx)
	require.NoError(t, err)
	output, err := exec.CommandContext(ctx, "docker", "run", "--rm", "--network", "none",
		"--volume", destination+":/workspace/output", "--workdir", "/workspace/output",
		"--entrypoint", "goimports", img.FullName(), "-d", ".").CombinedOutput()
	require.NoError(t, err, "%s", output)
	require.Empty(t, output, "GenerateGRPC returned Go that still needs the companion's formatting pass")

	// api.proto imports google/api/annotations.proto, and protoc-gen-go names
	// its package absolutely: a local copy would be a second registration of
	// the same file in the consumer's descriptor pool.
	_, err = os.Stat(filepath.Join(destination, "google"))
	require.True(t, os.IsNotExist(err), "Go bindings reference googleapis upstream, so nothing is generated for it")
}

func TestFormatGoOutputsPreservesHandwrittenFiles(t *testing.T) {
	ctx := t.Context()
	testutil.RequireProtoImage(t, ctx)
	root := t.TempDir()
	files := map[string]string{
		"go.mod":           "module example.test/formatter\n\ngo 1.27.0\n",
		"jobs/v1/types.go": "package jobsv1\nconst Value=1\n",
		"generated/account.pb.go": `// Code generated by protoc-gen-go. DO NOT EDIT.
package generated
import (
"fmt"
"example.test/formatter/jobs/v1"
)
var _ = fmt.Sprint(jobsv1.Value)
`,
		"handwritten.go":     "package formatter\nconst description = `\n// Code generated elsewhere. DO NOT EDIT.\n`\nconst Value=1\n",
		"proto/buf.gen.yaml": "version: v2\nplugins:\n  - local: protoc-gen-go\n    out: ..\n",
	}
	for name, content := range files {
		file := filepath.Join(root, name)
		require.NoError(t, os.MkdirAll(filepath.Dir(file), 0o750))
		require.NoError(t, os.WriteFile(file, []byte(content), 0o600))
	}
	img, err := proto.CompanionImage(ctx)
	require.NoError(t, err)
	runner, err := companion.NewCompanionRunner(ctx, companion.CompanionOpts{
		Name: "format-" + filepath.Base(root), SourceDir: root,
		Image: img, PreferredBackend: companion.BackendDocker,
	})
	require.NoError(t, err)
	runner.WithMount(root, "/workspace")
	runner.WithWorkDir("/workspace")
	runner.WithPause()
	t.Cleanup(func() {
		cleanup, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		require.NoError(t, runner.Shutdown(cleanup))
	})
	require.NoError(t, runner.Init(ctx))
	require.NoError(t, proto.FormatGoOutputs(ctx, runner, filepath.Join(root, "proto"), "buf.gen.yaml", root, "/workspace"))
	generated, err := os.ReadFile(filepath.Join(root, "generated/account.pb.go"))
	require.NoError(t, err)
	require.Contains(t, string(generated), `jobsv1 "example.test/formatter/jobs/v1"`)
	for _, name := range []string{"handwritten.go", "jobs/v1/types.go"} {
		got, err := os.ReadFile(filepath.Join(root, name))
		require.NoError(t, err)
		require.Equal(t, files[name], string(got))
	}
	proc, err := runner.NewProcess("go", "test", "./...")
	require.NoError(t, err)
	proc.WithDir("/workspace")
	require.NoError(t, proc.Run(ctx))
}

func TestGeneratePythonGRPC(t *testing.T) {
	wool.SetGlobalLogLevel(wool.DEBUG)
	ctx := context.Background()

	testutil.RequireProtoImage(t, ctx)

	apiProto := filepath.Join(testdataDir(t), "api.proto")
	ep := &resources.Endpoint{Module: "app", Service: "svc", Name: "api", Visibility: "private"}
	api, err := resources.LoadGrpcAPI(ctx, shared.Pointer(apiProto))
	require.NoError(t, err)
	grpc, err := resources.NewAPI(ctx, ep, resources.ToGrpcAPI(api))
	require.NoError(t, err)
	destination := t.TempDir()

	err = proto.GenerateGRPC(ctx, languages.PYTHON, destination, "app/svc", grpc)
	require.NoError(t, err, "proto companion image not built: %s", testutil.BuildCompanionsHint)

	for _, name := range []string{"app_svc_api_pb2.py", "app_svc_api_pb2_grpc.py"} {
		require.FileExists(t, filepath.Join(destination, name))
	}
}

func TestGenerateRustGRPC(t *testing.T) {
	wool.SetGlobalLogLevel(wool.DEBUG)
	ctx := context.Background()

	testutil.RequireProtoImage(t, ctx)

	apiProto := filepath.Join(testdataDir(t), "api.proto")
	ep := &resources.Endpoint{Module: "app", Service: "svc", Name: "api", Visibility: "private"}
	api, err := resources.LoadGrpcAPI(ctx, shared.Pointer(apiProto))
	require.NoError(t, err)
	grpc, err := resources.NewAPI(ctx, ep, resources.ToGrpcAPI(api))
	require.NoError(t, err)
	destination := t.TempDir()

	err = proto.GenerateGRPC(ctx, languages.RUST, destination, "app/svc", grpc)
	require.NoError(t, err, "proto companion image not built: %s", testutil.BuildCompanionsHint)

	// prost + tonic emit per proto package ("api/"): messages in api.rs,
	// the tonic client in api.tonic.rs.
	for _, name := range []string{"api/api.rs", "api/api.tonic.rs"} {
		require.FileExists(t, filepath.Join(destination, name))
	}
}

// TestGenerateTypeScriptGRPC covers the namespaces protoc-gen-es imports by a
// path relative to the bindings rather than from @bufbuild/protobuf/wkt. buf
// generates nothing for a dependency module, so without being told otherwise it
// emits the module's bindings alone and every one of those imports dangles.
//
// Only tsc catches it: generation succeeds either way and what it writes is
// well-formed TypeScript that happens to import files nothing wrote.
func TestGenerateTypeScriptGRPC(t *testing.T) {
	wool.SetGlobalLogLevel(wool.DEBUG)
	ctx := context.Background()

	testutil.RequireProtoImage(t, ctx)

	annotatedProto := filepath.Join(testdataDir(t), "annotated.proto")
	ep := &resources.Endpoint{Module: "app", Service: "svc", Name: "api", Visibility: "private"}
	api, err := resources.LoadGrpcAPI(ctx, shared.Pointer(annotatedProto))
	require.NoError(t, err)
	grpc, err := resources.NewAPI(ctx, ep, resources.ToGrpcAPI(api))
	require.NoError(t, err)
	destination := t.TempDir()

	err = proto.GenerateGRPC(ctx, languages.TYPESCRIPT, destination, "app/svc", grpc)
	require.NoError(t, err, "proto companion image not built: %s", testutil.BuildCompanionsHint)

	for _, name := range []string{
		"app_svc_api_pb.ts",
		"google/api/annotations_pb.ts",
		"buf/validate/validate_pb.ts",
	} {
		require.FileExists(t, filepath.Join(destination, filepath.FromSlash(name)),
			"the bindings import %s relatively, so the library has to own it", name)
	}

	_, err = os.Stat(filepath.Join(destination, "google", "protobuf"))
	require.True(t, os.IsNotExist(err),
		"the well-known types come from @bufbuild/protobuf/wkt; a local copy is one Timestamp the consumer's is not")

	bindings, err := os.ReadFile(filepath.Join(destination, "app_svc_api_pb.ts"))
	require.NoError(t, err)
	require.Contains(t, string(bindings), "@bufbuild/protobuf/wkt")

	tsc(t, ctx, destination)
}
