name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3


    - name: cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Latest
        version: v1.55

    - name: generate test generate coverage
      run: go test ./... -coverprofile=./cover.out

    - name: check test coverage
      id: coverage ## this step must have id
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        local-prefix: github.com/codefly-dev/core
        threshold-file: 0
        threshold-package: 10
        threshold-total: 10

    - name: make coverage badge
      uses: action-badges/core@0.2.2
      if: contains(github.ref, 'main')
      with:
        label: coverage
        message: ${{ steps.coverage.outputs.badge-text }}
        message-color: ${{ steps.coverage.outputs.badge-color }}
        file-name: coverage.svg
        badge-branch: badges ## orphan branch where badge will be committed
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: test with race detection
      run: go test -race ./... -v